---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

In the spirit of reproducibility this project website is created that outlines analysis done relating to analysis of Australian ticks.
 
Project website available here http://siobhonlegan.com/wildlife-ticks/ and source code is available at https://github.com/siobhon-egan/wildlife-ticks/

Illumina MiSeq data generated from the metabarcoding of ticks targeting the 12S rRNA locus has been deposited in the European nucleotide archive under the project accession number PRJEB46056 (ERP130244), which includes the following sample accession numbers: ERS6635126--ERS6635348 (BioSample # SAMEA8952359--SAMEA8952582)

Nucleotide data for subset of zOTUs generated are available in for the molecular identification of ticks has been uploaded to GenBank under accession numbers MW665133--MW665150.

Nucleotide data for MSLT barcode sequence data produced by Sanger sequencing has been deposited in GenBank under the following accession numbers

- OM791407--OM791437 (COI)
- OM756760--OM756765 (18S)
- OM830716--OM830764 (12S)
- OM830384--OM830429 (16S)

